site_name: react-localize-redux
repo_url: https://github.com/ryandrewjohnson/react-localize-redux
site_description: 'Localization library for React/Redux.'
site_author: Ryan Johnson

pages:
- index.md
- Getting Started: getting-started.md
- Formatting Translation Data: formatting-translation-data.md
- Features: features.md
- FAQ: faq.md
- API Documentation: 
  - 'Action Creators': 'api/action-creators.md'
  - 'Selectors': 'api/selectors.md'
  - 'Translate': 'api/translate.md'
  - 'localize - deprecated!': 'api/localize.md'

theme: readthedocs
# theme_dir: cinder

extra_css:
    - css/highlight-fix.css
    - css/highlight.css